
spring:
  redis:
    port: 6379
    password: 123456
    host: 127.0.0.1
    database: 0
  datasource:
    driver-class-name: oracle.jdbc.OracleDriver  #oracle驱动
    url: jdbc:oracle:thin:@test.sidb.jshrss:1521/CS_DZDA
    username: DZDA
    password: tqFYGxTTEUek
server:
  port: 80
